### ISSUE TITLE
Microverse Project: Set up your Kanban board

### ISSUE THREAD

**Issue by jose-Abel** [thankgodr/javascriptCapstoneProject#21]
Hello,
This is the issue opened for Review of the Microverse Project: Set up your Kanban board.
- We copy the Template Kanban Board from repo https://github.com/microverseinc/curriculum-javascript/projects/1 to this repo.
- We install jq tool locally on our pc's.
- We clone the repo https://github.com/microverseinc/curriculum-tools-copy-projects.git and run the copy_github_board.sh bash script so it copy all of the cards from the Kanban Board to our project repo.

Link for our Github repository: https://github.com/thankgodr/javascriptCapstoneProject
On our team there's 2 people, ThankGod Richard and Jose Abel.

Cheers.

**Comment by carlos-ssh** [comment]
Hi @jose-Abel , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- All cards are assigned to team members. You should see a circle with user's avatar on each card. See the example below:
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/22258274/136834113-a844cf98-21fe-49f3-9630-4ad5018fb6db.png">



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SpaYco** [comment]
Hello 👋,

_This is an additional review as a result of the second opinion request._

You're right, since your group consists of 2 people, Student C cards wouldn't have anyone assigned to them.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

**Comment by EricMbouwe** [comment]
### Hi @jose-Abel and @thankgodr, 

# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
